name: example
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart:
  type_ahead_text_field:
    path: ../

flutter:

  uses-material-design: true